"""
Student information for this assignment:

Replace <FULL NAME> with your name.
On my/our honor, <Jorge Nunez> and <Vivian Zhang>, this
programming assignment is my own work and I have not provided this code to
any other student.

I have read and understand the course syllabus's guidelines regarding Academic
Integrity. I understand that if I violate the Academic Integrity policy (e.g.
copy code from someone else, have the code generated by an LLM, or give my
code to someone else), the case shall be submitted to the Office of the Dean of
Students. Academic penalties up to and including an F in the course are likely.

UT EID 1: jn29423
UT EID 2: wz5363
"""

class Node:
    """
    A modified version of the Node class for linked lists (using proper class
    coding practices). Instead of a data instance variable, this node class has both
    a coefficient and an exponent instance variable, which is used to represent each
    term in a polynomial.
    """

    def __init__(self, coeff, exp, link=None):
        """
        Node Constructor for polynomial linked lists.

        Args:
        - coeff: The coefficient of the term.
        - exp: The exponent of the term.
        - link: The next node in the linked list.
        """
        self.coeff = coeff
        self.exp = exp
        self.next = link

    @property
    def coeff(self):
        """
        Getter method for the coefficient attribute.
        """
        return self.__coeff

    @coeff.setter
    def coeff(self, value):
        """
        Setter method for the coefficient attribute.
        """
        if value is None or isinstance(value, int):
            self.__coeff = value
        else:
            raise ValueError("Coefficient must be an integer or None.")

    @property
    def exp(self):
        """
        Getter method for the exponent attribute.
        """
        return self.__exp

    @exp.setter
    def exp(self, value):
        """
        Setter method for the exponent attribute.
        """
        if value is None or isinstance(value, int):
            self.__exp = value
        else:
            raise ValueError("Exponent must be an integer or None.")

    @property
    def next(self):
        """
        Getter method for the next attribute.
        """
        return self.__next

    @next.setter
    def next(self, value):
        """
        Setter method for the next attribute.
        """
        if value is None or isinstance(value, Node):
            self.__next = value
        else:
            raise ValueError("Next must be a Node instance or None.")

    def __str__(self):
        """
        String representation of each term in a polynomial linked list.
        """
        return f"({self.coeff}, {self.exp})"


class LinkedList:
    "Initializing and definitng instance variables and methods for the linked list class."
    def __init__(self):
        # You are also welcome to use a sentinel/dummy node!
        # It is definitely recommended, which will we learn more
        # about in class on Monday 3/24. If you choose to use
        # a dummy node, comment out the self.head = None
        # and comment in the below line. We use None to make sure
        # if there is an error where you accidentally include the
        # dummy node in your calculation, it will throw an error.
        # self.dummy = Node(None, None)
        self.head = None
        self.size = 0

    # Insert the term with the coefficient coeff and exponent exp into the polynomial.
    # If a term with that exponent already exists, add the coefficients together.
    # You must keep the terms in descending order by exponent.
    def insert_term(self, coeff, exp):
        """
        Inserting a term with a coeff and exp into the polynomial."
        """
        term = Node(coeff, exp)

        # Keep track of whether coeff changes ??
        # Base cases
        if coeff == 0:
            return
        # empty list
        if self.head is None:
            self.head = term
            self.size += 1
            return
        # term is the biggest, insert at beginning
        if term.exp > self.head.exp:
            term.next = self.head
            self.head = term
            self.size += 1
            return
        current = self.head
        previous = None

        # Case 1 - exponent is in the linked list

        # Want to reach the term with matching exponents,
        # Have current point to the term w/ matching exponent
        # Keep track of previous if terms cancel out
        while current is not None:
            # Loops until the list reaches the end, adds coeffs
            # Together if a common exponent is found
            if current.exp == term.exp:
                current.coeff += term.coeff
                # if coefficient is 0
                if current.coeff == 0:
                    # Remove the node
                    if previous is None:
                        self.head = current.next
                    else:
                        previous.next = current.next
                    self.size -= 1
                return
            previous = current
            current = current.next
        # Skips current if the coeff sums to 0
        # if current is not None and current.coeff == 0:
        #     previous.next = current.next
        #     return

        # Case 2 - Exponent was not found, insert it at the end
        current = self.head # begins a new traversal thru the list
        while current.next is not None:
            current = current.next
            self.size += 1
        current = self.head
        previous = None
        while current is not None and current.exp > term.exp:
            previous = current
            current = current.next
        term.next = current
        # if the new term is the largest exponent so it needs to be the head
        if previous is None:
            self.head = term
        else: # normal insert 
            previous.next = term
        self.size += 1

    # Add a polynomial p to the polynomial and return the resulting polynomial as a new linked list.
    def add(self, p):
        """
        Adding polynomials together.
        """
        new_list = LinkedList()
        current = self.head
        current1 = p.head
        if current1 is None:
            return self
        if current is None:
            return p
        while current is not None:
            new_list.insert_term(current.coeff, current.exp)
            current = current.next
        while current1 is not None:
            new_list.insert_term(current1.coeff, current1.exp)
            current1 = current1.next
        return new_list

    # Multiply a polynomial p with the polynomial and return the product as a new linked list.
    def mult(self, p):
        """
        Multiplying polynomials, returning product as a linked list."""
        new_list = LinkedList()
        current = self.head
        current1 = p.head
        multiply_list = LinkedList()
        if current1 is None:
            return new_list
        if current is None:
            return new_list
        while current is not None and current1 is not None:
            multiply_list = LinkedList()
            while current1 is not None:
                new_coeff = current.coeff * current1.coeff
                if new_coeff == 0:
                    return
                new_exp = current.exp + current1.exp
                multiply_list.insert_term(new_coeff, new_exp)
                current1 = current1.next
            new_list = new_list.add(multiply_list)
            current = current.next
            current1 = p.head
        return new_list

    # Return a string representation of the polynomial.
    # Fails one test case i think bc of add function not working
    def __str__(self):
        term_list = []
        temp_str = ""
        final_str = ""
        if self.head is None:
            return ""
        # building string representation
        current = self.head
        # iterating through the entire list
        while current is not None:
            temp_str = f"({current.coeff}, {current.exp})"
            term_list.append(temp_str)
            current = current.next
        for elem in term_list:
            final_str += elem
            final_str += " + "
        return final_str[:-3]

def main():
    "Calling functions and reading from a file"
    # read data from stdin (terminal/file) using input() and create polynomial p

    # the first line in the text file is the length of the polynomial
    length = int(input())
    p = LinkedList()
    # loop through all the terms in the polynomial line by line
    for _ in range(length):
        line = input()
        # separates the coefficient and exponent into strings in a list
        line = line.split()
        coeff = int(line[0])
        exp = int(line[1])
        p.insert_term(coeff, exp)

    # read the blank line separating p and q
    input()
    
    # read data from stdin (terminal/file) using input() and create polynomial q

    # the first line in the text file is the length of the polynomial
    length = int(input())
    q = LinkedList()
    # loop through all the terms in the polynomial line by line
    for _ in range(length):
        line = input()
        # separates the coefficient and exponent into strings in a list
        line = line.split()
        coeff = int(line[0])
        exp = int(line[1])
        q.insert_term(coeff, exp)
    # get sum of p and q as a new linked list and print sum
    print(p.add(q))
    # get product of p and q as a new linked list and print product
    print(p.mult(q))

if __name__ == "__main__":
    main()
